version: '3.8'

services:
  #  mailcatcher:
  #    image: schickling/mailcatcher
  #    ports:
  #      - "1080:1080"
  #      - "1025:1025"
  web:
    image: antonio0911/petstagram
    build: ./petstagram
    command: bash -c "sleep 5 && python manage.py migrate && gunicorn petstagram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./staticfiles:/PyCharm Projects/petstagram-django/tmp/petstagram/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - petstagram/.env
    depends_on:
      - postgres
  #      - mailcatcher
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: toni1234
      POSTGRES_USER: toni
      POSTGRES_DB: petstagram_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web
