version: '3.8'

services:
  #  mailcatcher:
  #    image: schickling/mailcatcher
  #    ports:
  #      - "1080:1080"
  #      - "1025:1025"
  web:
    build: .
    command: bash -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
  #      - mailcatcher
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: toni1234
      POSTGRES_USER: toni
      POSTGRES_DB: petstagram_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data